### ISSUE TITLE
Broker not found in Kubernetes deployment

### ISSUE THREAD

**Issue by framctr** [apache/rocketmq-docker#52]
I'm trying to deploy rocketmq on my testing cluster. I started from the scripts provided in that repo, but they do not work. I modified them in the following way:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rocketmq-broker-log-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rocketmq-broker-store-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rocketmq-namesrv-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-broker-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: rocketmq-broker-log-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-broker-store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: rocketmq-broker-store-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-namesrv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: rocketmq-namesrv-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
    spec:
      containers:
      - name: namesrv
        image: myrepo/rocketmq:4.9.3-alpine
        command: ["sh", "mqnamesrv"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "400m"
        ports:
        - containerPort: 9876
        volumeMounts:
        - name: namesrv-log
          mountPath: /var/log
      volumes:
      - name: namesrv-log
        persistentVolumeClaim:
          claimName: rocketmq-namesrv-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-broker
  template:
    metadata:
      labels:
        app: rocketmq-broker
    spec:
      containers:
      - name: broker
        image: myrepo/rocketmq:4.9.3-alpine
        command: ["sh", "mqbroker", "-n", "localhost:9876"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "400m"
        ports:
        - containerPort: 10909
        - containerPort: 10911
        volumeMounts:
        - name: broker-log
          mountPath: /var/log
        - name: broker-store
          mountPath: /home/rocketmq
      volumes:
      - name: broker-log
        persistentVolumeClaim:
          claimName: rocketmq-broker-log-pvc
      - name: broker-store
        persistentVolumeClaim:
          claimName: rocketmq-broker-store-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
spec:
  type: NodePort
  selector:
    app: rocketmq-namesrv
  ports:
  - name: namesrv
    port: 9876

---

apiVersion: v1
kind: Service
metadata:
  name: rocketmq-broker
spec:
  type: NodePort
  selector:
    app: rocketmq-broker
  ports:
  - name: broker1
    port: 10909
  - name: broker2
    port: 10911
```

The image `rocketmq:4.9.3-alpine` was created following the procedure on that repo.

After the deployment the rocketmq-namesrv works, but the broker's pod logs: `sh: can't open 'mqbroker': No such file or directory`...

_What could it be? Am I making something wrong?_
