### ISSUE TITLE
The broker keeping crashing when I run docker-compose

### ISSUE THREAD

**Issue by DraperHXY** [apache/rocketmq-docker#7]
This docker-compose script from [rocketmq-docker](https://github.com/apache/rocketmq-docker)
When I run this script, The broker has crashing after nameserv startup
``docker-compose.yml``
```yaml
version: '2'
services:
  namesrv:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
      - ./data/namesrv/store:/home/rocketmq/store
    command: sh mqnamesrv
  broker:
    image: rocketmqinc/rocketmq:4.4.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
```

``broker.conf``

```bash
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
#set `brokerIP1` if you want to set physical IP as broker IP.
namesrvAddr = 外网ip:9876
brokerIP1 = 外网ip
```

My server is ``Ubuntu 18.04``

Is this a bug?
