### ISSUE TITLE
求助 单机通过docker-compose部署5.1.3

### ISSUE THREAD

**Issue by CyJaySong** [apache/rocketmq-docker#88]
使用 docker-compose 在docker 部署5.1.3的namesrv 和 broker 用于开发测试，都启动正常了，但是sdk愣是连接不上，搜了一下，需要启动代理，但是在broker启动时添加了 --enable-proxy 还是不能正常连接，有朋友可以指导一下吗？或者有朋友有现成的docker-compose.yml文件么

**Comment by francisoliverlee** [comment]
can you share you docker-compose.yaml ?

**Comment by CyJaySong** [comment]
```
version: "3"
services:
  #Service for nameserver
  namesrv:
    container_name: RocketMQ-namesrv
    image: apache/rocketmq:5.1.3
    command: sh mqnamesrv
    labels:     
      createdBy: Apps
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./namesrv/logs:/home/rocketmq/logs


  #Service for broker
  broker:
    container_name: RocketMQ-broker
    links:
      - namesrv
    image: apache/rocketmq:5.1.3
    command: sh mqbroker --enable-proxy -c /opt/rocketmq/conf/broker.conf
    labels:     
      createdBy: Apps
    restart: always
    ports:
      - 8080:8080
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./broker/logs:/home/rocketmq/logs
      - ./broker/store:/home/rocketmq/store
      - ./broker/conf:/opt/rocketmq/conf
```
